# Default Configuration File for LiveBroadcast, color-codes are supported
title: '&6[&aLive&9Broadcast&6]&b'
timer: 30
'1': 'This is a line w&dith a special color!'
'2': This plugin allows you to have as many lines as you want!
